version: '3.8'

services:

  mysql:
    image: mysql:8.0.34-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
    ports:
      - "6603:3306"
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
